language: c
sudo: false
branches:
  only:
    - master
compiler:
  - clang
  - gcc
  
addons:
  apt:
    packages:
    - libhiredis-dev
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      git clone https://github.com/msempere/redispool.git;
      cd redispool;
      make;
      sudo make install;
      cd ..;
    fi
env:
    - CFLAGS="-Werror"
script: make $TARGET CFLAGS="$CFLAGS" && make $TARGET_VARS redispool-example
