language: c
sudo: required
branches:
  only:
    - master
compiler:
  - clang
  - gcc
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get install libhiredis-dev
      git clone https://github.com/msempere/redispool.git;
      cd redispool;
      make;
      sudo make install;
      cd ..;
    fi
env:
    - CFLAGS="-Werror"
script: make $TARGET CFLAGS="$CFLAGS" && make $TARGET_VARS redispool-example
